version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: saas_user
      POSTGRES_PASSWORD: saas_password
      POSTGRES_DB: saas_notes
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U saas_user -d saas_notes"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    environment:
      DATABASE_URL: "postgresql://saas_user:saas_password@postgres:5432/saas_notes"
      JWT_SECRET: "your-production-jwt-secret-change-this"
      NEXTAUTH_URL: "http://localhost:3000"
      NEXTAUTH_SECRET: "your-production-nextauth-secret-change-this"
      NODE_ENV: "production"
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data: 